name: Feature Branch Unit Tests & Integration Tests

on:
  push:
    branches-ignore:
      - 'master'
      - 'release*'
jobs:

  test:
    name: Unit Tests & Integration Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'
      - name: Maven Run Unit Test
        run: mvn -B clean test
      - name: Maven Run Integeration Test
        run: mvn -B verify -Pintegration-tests